platform :ios, '9.3'

target 'DetoxTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DetoxTest
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'

end
