# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DetoxTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DetoxTest
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/Performance', '~> 5.15.0'
  
end
